version: '3.9'

services:
  ds_api:
    container_name: ds_api
    restart: always
    build: .
    environment:
      APP_PORT: 3000
      APP_DEFAULT_PAGINATION_LIMIT: 25
      APP_MAX_PAGINATION_LIMIT: 1000
      APP_REQUIRE_API_KEY: 'true'
      APP_API_KEY: super-secret-api-key
      DB_NAME: admin
      DB_HOST: 10.0.0.4
      DB_PORT: 27017
      DB_USERNAME: root
      DB_PASSWORD: password
    ports:
      - 3000:3000
